    sources:
      - Playfair.glyphs
      - Playfair-Italic.glyphs
    axisOrder:
      - opsz
      - wdth
      - wght
      - ital
    familyName: Playfair
    buildStatic: false
    stat:
      Playfair[opsz,wdth,wght].ttf:
      - name: Optical size
        tag: opsz
        values:
        - name: 6pt
          value: 6
        - name: 8pt
          value: 8
        - name: 9pt
          value: 9
        - name: 10pt
          value: 10
        - name: 12pt
          value: 12
        - name: 16pt
          value: 16
        - name: 24pt
          value: 24
        - name: 36pt
          value: 36
        - name: 48pt
          value: 48
        - name: 72pt
          value: 72
        - name: 96pt
          value: 96
        - name: 144pt
          value: 144
      - name: Width
        tag: wdth
        values:
        - name: SemiCondensed
          value: 87.5
        - name: Normal
          value: 100
          flags: 2
        - name: SemiExpanded
          value: 112.5
        - name: Expanded
          value: 125
      - name: Weight
        tag: wght
        values:
        - name: Light
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
        - name: ExtraBold
          value: 800
        - name: Black
          value: 900
      - name: Italic
        tag: ital
        values:
        - name: Roman
          value: 0
          linkedValue: 1
          flags: 2
      Playfair-Italic[opsz,wdth,wght].ttf:
      - name: Optical size
        tag: opsz
        values:
        - name: 6pt
          value: 6
        - name: 8pt
          value: 8
        - name: 9pt
          value: 9
        - name: 10pt
          value: 10
        - name: 12pt
          value: 12
        - name: 16pt
          value: 16
        - name: 24pt
          value: 24
        - name: 36pt
          value: 36
        - name: 48pt
          value: 48
        - name: 72pt
          value: 72
        - name: 96pt
          value: 96
        - name: 144pt
          value: 144
      - name: Width
        tag: wdth
        values:
        - name: SemiCondensed
          value: 87.5
        - name: Normal
          value: 100
          flags: 2
        - name: SemiExpanded
          value: 112.5
        - name: Expanded
          value: 125
      - name: Weight
        tag: wght
        values:
        - name: Light
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
        - name: ExtraBold
          value: 800
        - name: Black
          value: 900
      - name: Italic
        tag: ital
        values:
        - name: Italic
          value: 1



      #cmd+shift+/